name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "poetry!=1.4.1"
        poetry --version
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest --version
        poetry run pytest --cov=py4vasp --cov-report term
    - name: Check code style
      run: |
        poetry run isort --version
        poetry run isort --check src
        poetry run isort --check tests
        poetry run black --version
        poetry run black --check src
        poetry run black --check tests


  test-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
    - name: Install dependencies with conda
      run: |
        conda info
        conda install -c conda-forge mdtraj
    - name: Install py4vasp
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest hypothesis
        pytest --version
        pytest --cov=py4vasp --cov-report term
    - name: Check code style
      run: |
        pip install black isort
        isort --version
        isort --check src
        isort --check tests
        black --version
        black --check src
        black --check tests
        #    - name: Install poetry
        #      run: |
        #        python -m pip install --upgrade pip
        #        pip install "poetry!=1.4.1"
        #        poetry --version
        #    - name: Install py4vasp
        #      run: |
        #        poetry config virtualenvs.create false --local
        #        poetry install
        #    - name: Test with pytest
        #      run: |
        #        poetry run pytest --version
        #        poetry run pytest --cov=py4vasp --cov-report term
        #    - name: Check code style
        #      run: |
        #        poetry run isort --version
        #        poetry run isort --check src
        #        poetry run isort --check tests
        #        poetry run black --version
        #        poetry run black --check src
        #        poetry run black --check tests
